apiVersion: apps/v1
kind: Deployment
metadata:
  name: omni-infra-provider-libvirt
  labels:
    app.kubernetes.io/name: omni-infra-provider-libvirt
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: omni-infra-provider-libvirt
  template:
    metadata:
      labels:
        app.kubernetes.io/name: omni-infra-provider-libvirt
    spec:
      containers:
        - name: provider
          image: ghcr.io/siderolabs/omni-infra-provider-libvirt:v0.1.0
          imagePullPolicy: IfNotPresent
          args:
            - --config-file=/config/config.yaml
          env:
            - name: USER
              value: omni
          envFrom:
            - secretRef:
                name: omni-infra-provider-libvirt
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
            - name: ssh-key
              mountPath: /.ssh
              readOnly: true
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: config
          configMap:
            name: omni-infra-provider-libvirt-config
        - name: ssh-key
          secret:
            secretName: omni-infra-provider-libvirt-ssh
            defaultMode: 0400
