apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: omni-infra-provider
resources:
  - namespace.yaml
  - deployment.yaml
configMapGenerator:
  - name: omni-infra-provider-libvirt-config
    files:
      - config.yaml
generatorOptions:
  disableNameSuffixHash: true
