apiVersion: v1
kind: Secret
metadata:
  name: omni-infra-provider-libvirt
  namespace: omni-infra-provider
type: Opaque
stringData:
  OMNI_ENDPOINT: https://omni.example.internal
  OMNI_SERVICE_ACCOUNT_KEY: replace-me
---
apiVersion: v1
kind: Secret
metadata:
  name: omni-infra-provider-libvirt-ssh
  namespace: omni-infra-provider
type: Opaque
stringData:
  id_rsa: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    replace-me
    -----END OPENSSH PRIVATE KEY-----
